from langchain.llms import HuggingFacePipeline
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import pandas as pd
from transformers import DebertaConfig, DebertaModel

#Load deberta model
model_name = "microsoft/deberta-base" 
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

deberta_pipeline = HuggingFacePipeline.from_model_and_tokenizer(
    model=model,
    tokenizer=tokenizer,
    task="text-classification" # Adjust task as needed
)

#insert training data
training_data = [
    {"text": "Yerba Mate Can", "label": 1}, 
    {"text": "Ceramics", "label": 0},
    {"text": "3d glasses", "label": 1}, 
    {"text": "pottery", "label": 0},
    {"text": "35mm film", "label": 1}, 
    {"text": "brightly died paper", "label": 0},
    {"text": "aluminum can", "label": 1}, 
    {"text": "hazardous waste", "label": 0},
    {"text": "antifreeze", "label": 1}, 
    {"text": "used paper towls", "label": 0},
    {"text": "deodorant sticks", "label": 1}, 
    {"text": "k cups", "label": 0},
    {"text": "5 gallon water jugs", "label": 1}, 
    {"text": "instant coffee pods", "label": 0},
    {"text": "55 gallon drums", "label": 1}, 
    {"text": "individual coffee creamers", "label": 0},
    {"text": "aerosol cans", "label": 1}, 
    {"text": "plastic coffee stirrers", "label": 0},
    {"text": "appliances", "label": 1}, 
    {"text": "plastic straws", "label": 0},
    {"text": "backpacks", "label": 1}, 
    {"text": "paper towels", "label": 0},
    {"text": "nicad batteries", "label": 1}, 
    {"text": "tissues", "label": 0},
    {"text": "batteries", "label": 1}, 
    {"text": "food wrapers", "label": 0},
    {"text": "rechargeable batteries", "label": 1}, 
    {"text": "chip bags", "label": 0},
    {"text": "beach balls", "label": 1}, 
    {"text": "Candy wrapper", "label": 0},
    {"text": "12 volt batteries", "label": 1}, 
    {"text": "sandwich wrapers", "label": 0},
    {"text": "9 volt batteries", "label": 1}, 
    {"text": "microwaveable meal packages", "label": 0},
    {"text": "beach balls", "label": 1}, 
    {"text": "zip lock bags", "label": 0},
    {"text": "books", "label": 1}, 
    {"text": "plastic bags", "label": 0},
    {"text": "plastic bottle caps", "label": 1}, 
    {"text": "syrup bottles", "label": 0},
    {"text": "metal bottle caps", "label": 1}, 
    {"text": "styrofoam", "label": 0},
    {"text": "alkaline batteries", "label": 1}, 
    {"text": "paper cups", "label": 0},
    {"text": "carbon-zinc batteries", "label": 1}, 
    {"text": "food", "label": 0},
    {"text": "hybrid car batteries", "label": 1}, 
    {"text": "meat packages", "label": 0},
    {"text": "laptop batteries", "label": 1}, 
    {"text": "chicken packages", "label": 0},
    {"text": "lead acid batteries", "label": 1}, 
    {"text": "food contaminated cardboard", "label": 0},
    {"text": "lithium ion batteries", "label": 1}, 
    {"text": "plastic lids", "label": 0},
    {"text": "bubble wrap", "label": 1}, 
    {"text": "packing peanuts", "label": 0},
    {"text": "5 gallon plastic buckets", "label": 1}, 
    {"text": "egg cartons", "label": 0},
    {"text": "metal buckets", "label": 1}, 
    {"text": "foam coffee cups", "label": 0},
    {"text": "butane cans", "label": 1}, 
    {"text": "foam plates", "label": 0},
    {"text": "cameras", "label": 1}, 
    {"text": "fast food containers", "label": 0},
    {"text": "candles", "label": 1}, 
    {"text": "foam meat trays", "label": 0},
    {"text": "christmas tree", "label": 1}, 
    {"text": "plastic straws", "label": 0},
    {"text": "clothes", "label": 1}, 
    {"text": "plastic bags", "label": 0},
    {"text": "carpeting", "label": 1}, 
    {"text": "plastic wrap", "label": 0},
    {"text": "car seats", "label": 1}, 
    {"text": "hardcover books", "label": 0},
    {"text": "cars", "label": 1}, 
    {"text": "shower curtains", "label": 0},Ó
    {"text": "cassette tapes", "label": 1}, 
    {"text": "waxed paper", "label": 0},
    {"text": "8 track tapes", "label": 1}, 
    {"text": "butcher paper", "label": 0},
    {"text": "vhs tapes", "label": 1}, 
    {"text": "bubble wrap", "label": 0},
    {"text": "CDs", "label": 1}, 
    {"text": "wrapping paper", "label": 0},
    {"text": "DVDs", "label": 1}, 
    {"text": "gift bags", "label": 0},
    {"text": "Jewel cases", "label": 1}, 
    {"text": "greeting cards", "label": 0},
    {"text": "Cell phones", "label": 1}, 
    {"text": "scrapbook paper", "label": 0},
    {"text": "Compact Fluorescent light bulbs", "label": 1}, 
    {"text": "glitter paper", "label": 0},
    {"text": "computers", "label": 1}, 
    {"text": "shopping receipts", "label": 0},
    {"text": "concrete", "label": 1}, 
    {"text": "soft plastic", "label": 0},
    {"text": "cooking oil", "label": 1}, 
    {"text": "napkins", "label": 0},
    {"text": "metal pots", "label": 1}, 
    {"text": "waterproof cardboard", "label": 0},
    {"text": "metal pans", "label": 1}, 
    {"text": "Crayons", "label": 1}, 
    {"text": "Mirrors", "label": 0},
    {"text": "crocs", "label": 1}, 
    {"text": "Metal oil cans", "label": 0},
    {"text": "Dehumidifier", "label": 1}, 
    {"text": "olive oil container", "label": 0},
    {"text": "denim", "label": 1}, 
    {"text": "coconut oil can", "label": 0},
    {"text": "dishwashers", "label": 1}, 
    {"text": "paint cans", "label": 0},
    {"text": "drywall", "label": 1}, 
    {"text": "Crystal", "label": 0},
    {"text": "egg shells", "label": 1}, 
    {"text": "Diapers", "label": 0},
    {"text": "electronic waste", "label": 1}, 
    {"text": "household glass", "label": 0},
    {"text": "empty cleaning products", "label": 1}, 
    {"text": "hazardous waste", "label": 0},
    {"text": "engine coolant", "label": 1}, 
    {"text": "medical waste", "label": 0},
    {"text": "rubber gloves", "label": 1}, 
    {"text": "coated cardboard", "label": 0},
    {"text": "goldenrod envelopes", "label": 1}, 
    {"text": "syringes", "label": 0},
    {"text": "padded envelopes", "label": 1}, 
    {"text": "tubing", "label": 0},
    {"text": "tyvek envelopes", "label": 1}, 
    {"text": "scalpels", "label": 0},
    {"text": "plastic window envelopes", "label": 1}, 
    {"text": "biohazards", "label": 0},
    {"text": "eyeglasses", "label": 1}, 
    {"text": "human waste", "label": 0},
    {"text": "fabrics", "label": 1}, 
    {"text": "grease", "label": 0},
    {"text": "textiles", "label": 1}, 
    {"text": "plastic bags", "label": 0},
    {"text": "file folders", "label": 1}, 
    {"text": "plastic wrap", "label": 0},
    {"text": "film canisters", "label": 1}, 
    {"text": "plastic grocery bags", "label": 0},
    {"text": "fire exstinguishers", "label": 1}, 
    {"text": "plastic shopping bags", "label": 0},
    {"text": "floppy disks", "label": 1}, 
    {"text": "plastic coated boxes", "label": 0},
    {"text": "zip disks", "label": 1}, 
    {"text": "plastic screw on tops", "label": 0},
    {"text": "3.5 inch disks", "label": 1}, 
    {"text": "shredded paper", "label": 0},
    {"text": "fluorescent bulbs", "label": 1}, 
    {"text": "unmarked items", "label": 0},
    {"text": "food processors", "label": 1}, 
    {"text": "wet paper", "label": 0},
    {"text": "food waste", "label": 1}, 
    {"text": "wires", "label": 0},
    {"text": "formal wear", "label": 1}, 
    {"text": "squeeze bottles", "label": 0},
    {"text": "freon", "label": 1}, 
    {"text": "coffee cup lids", "label": 0},
    {"text": "furniture", "label": 1}, 
    {"text": "to-go containers", "label": 0},
    {"text": "gaming consoles", "label": 1}, 
    {"text": "kitty litter buckets", "label": 0},
    {"text": "garden hose", "label": 1}, 
    {"text": "animal waste", "label": 0},
    {"text": "gasoline", "label": 1}, 
    {"text": "kitty litter", "label": 0},
    {"text": "gift cards", "label": 1}, 
    {"text": "laundry baskets", "label": 0},
    {"text": "glasses", "label": 1}, 
    {"text": "straws", "label": 0},
    {"text": "glass bottles", "label": 1}, 
    {"text": "solo cups", "label": 0},
    {"text": "glass windows", "label": 1}, 
    {"text": "plastic toys", "label": 0},
    {"text": "glue containers", "label": 1}, 
    {"text": "mcdonalds toys", "label": 0},
    {"text": "golf balls", "label": 1}, 
    {"text": "plastic egg cartons", "label": 0},
    {"text": "grass clippings", "label": 1}, 
    {"text": "sippy cups", "label": 0},
    {"text": "greeting cards", "label": 1}, 
    {"text": "refilled containers", "label": 0},
    {"text": "grey water", "label": 1}, 
    {"text": "plastic utensils", "label": 0},
    {"text": "plastic hangers", "label": 1}, 
    {"text": "cups coated in plastic", "label": 0},
    {"text": "wire hangers", "label": 1}, 
    {"text": "cups coated in wax", "label": 0},
    {"text": "hard drives", "label": 1}, 
    {"text": "chip bags", "label": 0},
    {"text": "HDPE plastic", "label": 1}, 
    {"text": "lays chip bags", "label": 0},
    {"text": "hearing aids", "label": 1}, 
    {"text": "doritos chip bags", "label": 0},
    {"text": "holiday cards", "label": 1}, 
    {"text": "electronics", "label": 0},
    {"text": "holiday lights", "label": 1}, 
    {"text": "food waste", "label": 0},
    {"text": "household hazardous waste", "label": 1}, 
    {"text": "flexible packages", "label": 0},
    {"text": "jam jars", "label": 1}, 
    {"text": "scrap metal", "label": 0},
    {"text": "jar lids", "label": 1}, 
    {"text": "sharp items", "label": 0},
    {"text": "jars", "label": 1}, 
    {"text": "knives", "label": 0},
    {"text": "jewelry", "label": 1}, 
    {"text": "colored paper", "label": 0},
    {"text": "juice boxes", "label": 1}, 
    {"text": "pretzel bags", "label": 0},
    {"text": "junk", "label": 1}, 
    {"text": "pretzel jugs", "label": 0},
    {"text": "junk mail", "label": 1}, 
    {"text": "flexible plastic", "label": 0},
    {"text": "kevlar", "label": 1}, 
    {"text": "garden hoses", "label": 0},
    {"text": "keyboards", "label": 1}, 
    {"text": "chains", "label": 0},
    {"text": "Keys", "label": 1}, 
    {"text": "leashes", "label": 0},
    {"text": "kitchen cabinets", "label": 1}, 
    {"text": "saws", "label": 0},
    {"text": "kitchen utensils", "label": 1}, 
    {"text": "coils", "label": 0},
    {"text": "knives", "label": 1}, 
    {"text": "skin care", "label": 0},
    {"text": "leather", "label": 1}, 
    {"text": "chemical waste", "label": 0},
    {"text": "legos", "label": 1}, 
    {"text": "old makeup", "label": 0},
    {"text": "license plates", "label": 1}, 
    {"text": "rotted food", "label": 0},
    {"text": "light bulbs", "label": 1}, 
    {"text": "flour bags", "label": 0},
    {"text": "lipstick", "label": 1}, 
    {"text": "egg shells", "label": 0},
    {"text": "lotion bottles", "label": 1}, 
    {"text": "cheese rind", "label": 0},
    {"text": "magazines", "label": 1}, 
    {"text": "tomato stems", "label": 0},
    {"text": "makeup", "label": 1}, 
    {"text": "corn husk", "label": 0},
    {"text": "manila folders", "label": 1}, 
    {"text": "black plastic", "label": 0},
    {"text": "mattresses", "label": 1}, 
    {"text": "plastic yard games", "label": 0},
    {"text": "medication", "label": 1}, 
    {"text": "darts", "label": 0},
    {"text": "mercury", "label": 1}, 
    {"text": "dartboard", "label": 0},
    {"text": "metal", "label": 1}, 
    {"text": "rubber", "label": 0},
    {"text": "microwaves", "label": 1}, 
    {"text": "solidified chees", "label": 0},
    {"text": "milk cartons", "label": 1}, 
    {"text": "artificial clothing", "label": 0},
    {"text": "milk jugs", "label": 1}, 
    {"text": "rylon", "label": 0},
    {"text": "mirrors", "label": 1}, 
    {"text": "crisps", "label": 0},
    {"text": "MP3 player", "label": 1}, 
    {"text": "styrofoam", "label": 0},
    {"text": "newspaper", "label": 1}, 
    {"text": "cream cheese", "label": 0},
    {"text": "nikes", "label": 1}, 
    {"text": "plants", "label": 0},
    {"text": "notebooks", "label": 1}, 
    {"text": "dirt", "label": 0},
    {"text": "spiralbound notebooks", "label": 1}, 
    {"text": "cardboard labels", "label": 0},
    {"text": "nylon", "label": 1}, 
    {"text": "coconut milk paper container", "label": 0},
    {"text": "packing peanuts", "label": 1}, 
    {"text": "rice milk paper container", "label": 0},
    {"text": "paint", "label": 1}, 
    {"text": "oat milk paper container", "label": 0},
    {"text": "paint cans", "label": 1}, 
    {"text": "almond milk paper container", "label": 0},
    {"text": "paper", "label": 1}, 
    {"text": "egg nog paper container", "label": 0},
    {"text": "paper shopping bags", "label": 1}, 
    {"text": "Macademia milk paper container", "label": 0},
    {"text": "pens", "label": 1}, 
    {"text": "ben and jerry's ice cream pint", "label": 0},
    {"text": "markers", "label": 1}, 
    {"text": "whipped cream can", "label": 0},
    {"text": "phone books", "label": 1}, 
    {"text": "granola package", "label": 0},
    {"text": "pizza boxes", "label": 1}, 
    {"text": "popcorn packages", "label": 0},
    {"text": "generic plastic", "label": 1}, 
    {"text": "coco powder container", "label": 0},
    {"text": "plastic #1", "label": 1}, 
    {"text": "rice cracker bag", "label": 0},
    {"text": "plastic #2", "label": 1}, 
    {"text": "shishito crisp bag", "label": 0},
    {"text": "plastic #3", "label": 1}, 
    {"text": "french onion popcorn bag", "label": 0},
    {"text": "Plastic #4", "label": 1}, 
    {"text": "cracker box", "label": 0},
    {"text": "Plastic #5", "label": 1}, 
    {"text": "nougut box", "label": 0},
    {"text": "paperback books", "label": 1}, 
    {"text": "chocolate wrapper", "label": 0},
    {"text": "plastic #7", "label": 1}, 
    {"text": "ham netting", "label": 0},
    {"text": "plastic bags", "label": 1}, 
    {"text": "salami bag", "label": 0},
    {"text": "plastic bottles", "label": 1}, 
    {"text": "fruit bag", "label": 0},
    {"text": "plastic packing pillows", "label": 1}, 
    {"text": "coffee bags", "label": 0},
    {"text": "Plastic toys", "label": 1}, 
    {"text": "salad bag", "label": 0},
    {"text": "plastic utensils", "label": 1}, 
    {"text": "dried fruit bags", "label": 0},
    {"text": "postits", "label": 1}, 
    {"text": "brie packaging", "label": 0},
    {"text": "prescription drugs", "label": 1}, 
    {"text": "hair oil packages", "label": 0},
    {"text": "printer ink cartridges", "label": 1}, 
    {"text": "veggies", "label": 0},
    {"text": "printer toner cartridges", "label": 1}, 
    {"text": "plastic bread bags", "label": 0},
    {"text": "printers", "label": 1}, 
    {"text": "butter stick wrappers", "label": 0},
    {"text": "propane tanks", "label": 1}, 
    {"text": "black microwavable bowls", "label": 0},
    {"text": "q-tips", "label": 1}, 
    {"text": "granola bar wrapper", "label": 0},
    {"text": "quartz", "label": 1}, 
    {"text": "baguette bag", "label": 0},
    {"text": "quilts", "label": 1}, 
    {"text": "stained brown paper bag", "label": 0},
    {"text": "rags", "label": 1}, 
    {"text": "fried pork rind bags", "label": 0},
    {"text": "refrigerators", "label": 1}, 
    {"text": "glass olive oil bottle", "label": 0},
    {"text": "roof shingles", "label": 1}, 
    {"text": "pea snack bag", "label": 0},
    {"text": "rubber", "label": 1}, 
    {"text": "plastic sheet cake pan", "label": 0},
    {"text": "rubber bands", "label": 1}, 
    {"text": "peanut bags", "label": 0},
    {"text": "rubber tires", "label": 1}, 
    {"text": "egg bite packaging", "label": 0},
    {"text": "wool rugs", "label": 1}, 
    {"text": "raman bag", "label": 0},
    {"text": "cotton rugs", "label": 1}, 
    {"text": "craker tins", "label": 0},
    {"text": "shoes", "label": 1}, 
    {"text": "tortilla bag", "label": 0},
    {"text": "keen shoes", "label": 1}, 
    {"text": "apple juice pouch", "label": 0},
    {"text": "sneakers", "label": 1}, 
    {"text": "hotdog packaging", "label": 0},
    {"text": "running shoes", "label": 1}, 
    {"text": "sushi packaging", "label": 0},
    {"text": "tennis shoes", "label": 1}, 
    {"text": "fish bones", "label": 0},
    {"text": "toms shoes", "label": 1}, 
    {"text": "animal bones", "label": 0},
    {"text": "shower curtains", "label": 1}, 
    {"text": "fish carcases", "label": 0},
    {"text": "shredded paper", "label": 1}, 
    {"text": "sushi trays", "label": 0},
    {"text": "six pack rings", "label": 1}, 
    {"text": "hot sauce packages", "label": 0},
    {"text": "smart phones", "label": 1}, 
    {"text": "sauce packages", "label": 0},
    {"text": "smoke detectors", "label": 1}, 
    {"text": "soy sauce packet", "label": 0},
    {"text": "soap", "label": 1}, 
    {"text": "bannana peel", "label": 0},
    {"text": "soap dispensers", "label": 1}, 
    {"text": "popsicle plastic packaging", "label": 0},
    {"text": "socks", "label": 1}, 
    {"text": "face masks", "label": 0},
    {"text": "sponges", "label": 1}, 
    {"text": "peanut butter protein bar", "label": 0},
    {"text": "sports gear", "label": 1}, 
    {"text": "freezed dried fruit bag", "label": 0},
    {"text": "sports equipment", "label": 1}, 
    {"text": "dog treat bags", "label": 0},
    {"text": "steel", "label": 1}, 
    {"text": "plastic plates", "label": 0},
    {"text": "stoves", "label": 1}, 
    {"text": "tofu packaging", "label": 0},
    {"text": "plastic #6", "label": 1}, 
    {"text": "oil slick", "label": 0},
    {"text": "T-shirts", "label": 1}, 
    {"text": "metal tools coated with plastic", "label": 0},
    {"text": "tablets", "label": 1}, 
    {"text": "half filled containers", "label": 0},
    {"text": "kindles", "label": 1}, 
    {"text": "string cheese wrappers", "label": 0},
    {"text": "ipads", "label": 1}, 
    {"text": "sticker backings", "label": 0},
    {"text": "takeout containers", "label": 1}, 
    {"text": "pen ink", "label": 0},
    {"text": "tech gadgets", "label": 1}, 
    {"text": "sharp metal", "label": 0},
    {"text": "tetra pak", "label": 1}, 
    {"text": "explosives", "label": 0},
    {"text": "textbooks", "label": 1}, 
    {"text": "pizza box", "label": 0},
    {"text": "three ring binders", "label": 1}, 
    {"text": "spray bottle caps", "label": 0},
    {"text": "tin cans", "label": 1}, 
    {"text": "perfume bottles", "label": 0},
    {"text": "tinfoil", "label": 1}, 
    {"text": "plastic padding", "label": 0},
    {"text": "tires", "label": 1}, 
    {"text": "deli packaging", "label": 0},
    {"text": "toothbrushes", "label": 1}, 
    {"text": "mochi rice bags", "label": 0},
    {"text": "toothpaste tubes", "label": 1}, 
    {"text": "essential oil glasses", "label": 0},
    {"text": "trophies", "label": 1}, 
    {"text": "lemon bags", "label": 0},
    {"text": "TVs", "label": 1}, 
    {"text": "cheese wrapping", "label": 0},
    {"text": "Umbrellas", "label": 1}, 
    {"text": "salt bags", "label": 0},
    {"text": "Used plastic wrap", "label": 1}, 
    {"text": "ruined towels", "label": 0},
    {"text": "VCR", "label": 1}, 
    {"text": "stale bread", "label": 0},
    {"text": "VHS tapes", "label": 1}, 
    {"text": "salmon tails", "label": 0},
    {"text": "Vinyl", "label": 1}, 
    {"text": "shells of fish", "label": 0},
    {"text": "Vinyl banners", "label": 1}, 
    {"text": "mousse cakes", "label": 0},
    {"text": "Vinyl records", "label": 1}, 
    {"text": "overnight oat container", "label": 0},
    {"text": "Vinyl siding", "label": 1}, 
    {"text": "mashed potato bag", "label": 0},
    {"text": "water bottles", "label": 1}, 
    {"text": "bag cheese", "label": 0},
    {"text": "water filters", "label": 1}, 
    {"text": "cigarette butts", "label": 0},
    {"text": "wheelchairs", "label": 1}, 
    {"text": "cigars", "label": 0},
    {"text": "wine bottles", "label": 1}, 
    {"text": "straw packaging", "label": 0},
    {"text": "wine corks", "label": 1}, 
    {"text": "cookie dough packaging", "label": 0},
    {"text": "wire", "label": 1}, 
    {"text": "sausage casings", "label": 0},
    {"text": "wood", "label": 1}, 
    {"text": "burrito packaging", "label": 0},
    {"text": "x-rays", "label": 1}, 
    {"text": "wet pasta packaging", "label": 0},
    {"text": "Xbox 360", "label": 1}, 
    {"text": "plastic k cups", "label": 0},
    {"text": "Yard waste", "label": 1}, 
    {"text": "turkey packaging", "label": 0},
    {"text": "yarn", "label": 1}, 
    {"text": "marshmellow bag", "label": 0},
    {"text": "yoga mats", "label": 1}, 
    {"text": "fruit rind", "label": 0},
    {"text": "yogurt cups", "label": 1}, 
    {"text": "plastic cookie trays", "label": 0},
    {"text": "zinc", "label": 1}, 
    {"text": "lettuce bag", "label": 0},
    {"text": "ziploc bags", "label": 1}, 
    {"text": "grape stems", "label": 0},
    {"text": "zippers", "label": 1},
    {"text": "organic waste", "label":0}

]



